name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/Hydrogen"
      - run: mv .env.example .env
      - run: npm ci
      - run: npm run build
      - run: npm run vitest
